apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-springboot
  name: example
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-springboot
  template:
    metadata:
      labels:
        app: java-springboot
    spec:
      containers:
      - image: local/example:latest
        imagePullPolicy: Never
        name: example

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: java-springboot
  name: example
  namespace: default
spec:
  ports:
  - nodePort: 30365
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: java-springboot
  type: NodePort
